// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC_ax1tVmsHtBrPiF2flPJ4BgyFmW2hJ8M',
    appId: '1:267566513472:web:769cae8f8009e6a86ecea5',
    messagingSenderId: '267566513472',
    projectId: 'proyecto-final-auth-69420',
    authDomain: 'proyecto-final-auth-69420.firebaseapp.com',
    storageBucket: 'proyecto-final-auth-69420.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBlrMBuaP8jTJBlXXYcFpk5hJixP8fbDaw',
    appId: '1:267566513472:ios:615b2530bbf61da36ecea5',
    messagingSenderId: '267566513472',
    projectId: 'proyecto-final-auth-69420',
    storageBucket: 'proyecto-final-auth-69420.firebasestorage.app',
    iosBundleId: 'com.example.proyectoFinal',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBlrMBuaP8jTJBlXXYcFpk5hJixP8fbDaw',
    appId: '1:267566513472:ios:615b2530bbf61da36ecea5',
    messagingSenderId: '267566513472',
    projectId: 'proyecto-final-auth-69420',
    storageBucket: 'proyecto-final-auth-69420.firebasestorage.app',
    iosBundleId: 'com.example.proyectoFinal',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC_ax1tVmsHtBrPiF2flPJ4BgyFmW2hJ8M',
    appId: '1:267566513472:web:4d8623b749254ac86ecea5',
    messagingSenderId: '267566513472',
    projectId: 'proyecto-final-auth-69420',
    authDomain: 'proyecto-final-auth-69420.firebaseapp.com',
    storageBucket: 'proyecto-final-auth-69420.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAta-KSihGk1icjFvNxs-TZoU7wNN81G9I',
    appId: '1:267566513472:android:91ae029b4a0c71d36ecea5',
    messagingSenderId: '267566513472',
    projectId: 'proyecto-final-auth-69420',
    storageBucket: 'proyecto-final-auth-69420.firebasestorage.app',
  );

}